### PR TITLE
Update Gradle to 7.2

### PR DESCRIPTION
**Pull request by ghost**
This is a simple PR for updating the gradle version

### CODE REVIEW

**Comment by greysilly7** [comment]
What are the benefits if upgrading to gradle 7.2?

**Comment by ghost** [comment]
Paper uses gradle 7.2 now

**Comment by TheArcaneBrony** [comment]
Again, what benefits? I've read over their changelogs and saw nothing interesting except less cache misses, which doesnt help us because we wipe the cache often anyways

**Review by Toffikk — COMMENTED** [review]
please update the gradle wrapper scripts to gradle 7.2 too , you need to run `./gradlew wrapper --gradle-version=7.2` twice for them to update , and use the `-all` distribution.

**Pull request closed without merging**
