### PR TITLE
Improve README.md

### PR DESCRIPTION
**Pull request by Pascalpex**

### CODE REVIEW

**Comment by TheArcaneBrony** [comment]
Github Action
Airplain
"Airplane fork based off of Airplain" Sherlock? Is that you?

**Comment by TheArcaneBrony** [comment]
Airplain?

**Comment by Kylepoops** [comment]
Sorry for my bad English Bruhhhhhh

**Comment by TheArcaneBrony** [comment]
not even your PR tho?

**Comment by Kylepoops** [comment]
> not even your PR tho?

The latest Readme is my commit

**Comment by TheArcaneBrony** [comment]
kyle nobody said merge

**Comment by Kylepoops** [comment]
> kyle nobody said merge

Ah sorry for that

**Pull request merged**
